### ISSUE TITLE
bit react feathers modules

### ISSUE THREAD

**Issue by idkjs** [celsobonutti/professor-escroto#2]
Hello @celsobonutti. I am studying your code and was wondering if it possible for you to share you  `bit.react-feathers` modules.

Thanks for sharing your example!

**Comment by celsobonutti** [comment]
Hey @idkjs! Sorry, I didn't quite get what you're asking for: do you want the bindings or the bit packages?
If it's the packages, they're in https://bit.dev/feathericons/react-feather.
If it's the bindings, I only did the ones I'm using in this project, sorry 😅

Thank you! I'm actually not working on this anymore but I hope I'll be back soon hahaha

**Comment by idkjs** [comment]
> If it's the packages, they're in https://bit.dev/feathericons/react-feather.

Thank you, sir.
